### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by hrh94** [nefe/number-precision#10]
-3000000000000000500 is beyond boundary when transfer to integer, the results may not be accurate

**Comment by yilikun** [comment]
i have the problem,too,can i stop it logging?

**Comment by gaochengyidlmu** [comment]
Me too.

49514898769934380 is beyond boundary when transfer to integer, the results may not be accurate

**Comment by gaochengyidlmu** [comment]
the page has many data to calculate, so it always print the warning log.

![image](https://user-images.githubusercontent.com/18210759/42256402-9a5ef984-7f83-11e8-905a-dcab6de39b28.png)

**Comment by camsong** [comment]
3000000000000000500 is bigger than `2^53=9007199254740992`, so JS can't calculate it precisely.

**Comment by tonghuashuo** [comment]
Any chance may there be an option to turn this off (like @babel/polyfill/noConflict). We know these warnings are reasonable. But it could be annoying if they come in flood. I wanna see my own warnings but they are buried in those.

**Comment by gaochengyidlmu** [comment]
@camsong Before I remove the warning, the page is slow.
Now, fixed.

**Comment by camsong** [comment]
@tonghuashuo good idea, you can use v1.3.1 to get disable warning.

https://github.com/nefe/number-precision/releases/tag/1.3.1
