### ISSUE TITLE
NP.divide(1, 3) = 0.333333333333

### ISSUE THREAD

**Issue by wangyupo** [nefe/number-precision#18]

**Comment by cbbfcd** [comment]
@wangyupo so, what's your doubts?

**Comment by lxfriday** [comment]
@wangyupo 这个貌似没有问题额， `1 / 3 === 0.3333333333333333`

**Comment by camsong** [comment]
Fixed by https://github.com/nefe/number-precision/pull/21
Great thanks to @lxfriday
