### ISSUE TITLE
33.3333除以100 在浏览器上计算出现问题

### ISSUE THREAD

**Issue by UnlimitedGalaxy** [nefe/number-precision#19]
NP.divide(33.3333, 100) = 0.33333300000000005

**Comment by lxfriday** [comment]
@UnlimitedGalaxy @camsong  浏览器和 node 表现不一致

`console.log('divide', divide(33.3333, 100), 33.3333 / 100);`

浏览器

```
divide 0.33333300000000005 0.333333
```

node v10.16.3

```
divide 0.333333 0.333333
```

**Comment by lxfriday** [comment]
@camsong  问题的环节定位到了

![image](https://user-images.githubusercontent.com/20264467/67172593-7f004180-f3ee-11e9-8ab0-c4aeb25c4780.png)

![image](https://user-images.githubusercontent.com/20264467/67172608-8d4e5d80-f3ee-11e9-99e3-1a64843b0d1f.png)

原因是 `Math.pow(10, 0 - 4)` => 在 Chrome 上  `0.00009999999999999999`，在 FF、IE、Edge、node 上都是 `0.0001`

在 `divide` 最后一步的计算就变成了 `times(3333.33, 0.00009999999999999999)`

接着 `float2Fixed(num2)` => `10000000000000000` 这个数已经超过了 `Number.MAX_SAFE_INTEGER `

![image](https://user-images.githubusercontent.com/20264467/67172844-7c521c00-f3ef-11e9-9e73-9c8d8d44444f.png)

后面的计算就没有意义了， `num1Changed * num2Changed` => 会变得更大
