### ISSUE TITLE
times 计算问题

### ISSUE THREAD

**Issue by caijf** [nefe/number-precision#28]
```javascript
NP.times(9999999999999.46, 100) // 999999999999945.9
```

这个结果是否有问题？

使用 [big.js](https://github.com/MikeMcl/big.js/) 计算结果为 `999999999999946`

可以参考我写的 [JS浮点数计算测试](https://2zbuy.csb.app/)

**Comment by camsong** [comment]
精度要求过高，建议使用 big.js
