### ISSUE TITLE
控制台warning

### ISSUE THREAD

**Issue by rickyrui** [nefe/number-precision#38]
![image](https://user-images.githubusercontent.com/48702854/91418235-77b68980-e884-11ea-840f-57d33521e2fd.png)
 31941166666666700 is beyond boundary when transfer to integer, the results may not be accurate
控制台warning

**Comment by cbbfcd** [comment]
bigInt.  like #15

**Comment by Mario34** [comment]
```js
let _boundaryCheckingState = true;
/**
 * 是否进行边界检查，默认开启
 * @param flag 标记开关，true 为开启，false 为关闭，默认为 true
 */
function enableBoundaryChecking(flag = true) {
  _boundaryCheckingState = flag;
}
```
[enableBoundaryChecking](https://github.com/nefe/number-precision/blob/b1bde33a39a23e4fc1f5251e3eaa593056960d00/src/index.ts#L121)
