### ISSUE TITLE
NP.times(9999999999999.46, 100)

### ISSUE THREAD

**Issue by iylu** [nefe/number-precision#6]
NP.times(9999999999999.46, 100)  ==>  999999999999945.9

13位9

The result is not equal to 999999999999946

**Comment by camsong** [comment]
This is because the precision of `9999999999999.46` equals to `999999999999946` is larger than `Math.abs(2, 53) = 9007199254740992`, so the result is not reliable

**Comment by ascoders** [comment]
This library does not make scene with large numbers.

**Comment by iylu** [comment]
thanks
